In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# read CSV
demographics = pd.read_csv('/content/drive/MyDrive/HTML final project/demographics.csv')

demographics['Gender'].replace(['Female', 'Male'], [0, 1],inplace = True)
demographics['Under 30'].replace(['No', 'Yes'], [0, 1],inplace = True)
demographics['Senior Citizen'].replace(['No', 'Yes'], [0, 1],inplace = True)
demographics['Married'].replace(['No', 'Yes'], [0, 1],inplace = True)
demographics['Dependents'].replace(['No', 'Yes'], [0, 1],inplace = True)

demographics

     Customer ID  Count  Gender  ...  Married  Dependents  Number of Dependents
0     1746-TGTWV    1.0     1.0  ...      0.0         0.0                   0.0
1     8499-BRXTD    1.0     0.0  ...      1.0         NaN                   1.0
2     2041-JIJCI    1.0     1.0  ...      0.0         1.0                   3.0
3     5832-EXGTT    1.0     0.0  ...      1.0         1.0                   1.0
4     8350-NYMVI    NaN     NaN  ...      NaN         1.0                   1.0
...          ...    ...     ...  ...      ...         ...                   ...
6158  7609-NRNCA    NaN     0.0  ...      0.0         0.0                   0.0
6159  4835-YSJMR    1.0     1.0  ...      NaN         1.0                   2.0
6160  5067-DGXLL    1.0     NaN  ...      1.0         1.0                   2.0
6161  3129-AAQOU    1.0     0.0  ...      1.0         1.0                   2.0
6162  2205-LPVGL    1.0     1.0  ...      0.0         0.0                   0.0

[6163 rows x 9 columns]

In [ ]:
print(demographics.isna().sum())
demographics.loc[demographics['Age'] < 30, ['Under 30']] = 1
demographics.loc[demographics['Age'] >= 30, ['Under 30']] = 0
demographics.loc[demographics['Age'] >= 65, ['Senior Citizen']] = 1
demographics.loc[demographics['Age'] < 65, ['Senior Citizen']] = 0
demographics.loc[demographics['Under 30'] == 1, ['Senior Citizen']] = 0
demographics.loc[demographics['Senior Citizen'] == 1, ['Under 30']] = 0
print(demographics.isna().sum())

Customer ID               0
Count                   770
Gender                  770
Age                     770
Under 30                770
Senior Citizen          770
Married                 770
Dependents              770
Number of Dependents    770
dtype: int64
Customer ID               0
Count                   770
Gender                  770
Age                     770
Under 30                 87
Senior Citizen           77
Married                 770
Dependents              770
Number of Dependents    770
dtype: int64

In [ ]:
under_30 = demographics[(demographics['Under 30'] == 1.0) & demographics['Age'].notnull()]
under_30_median_age = under_30['Age'].median()
print("under_30_median: ", under_30_median_age)

senior = demographics[(demographics['Senior Citizen'] == 1.0) & demographics['Age'].notnull()]
senior_median_age = senior['Age'].median()
print("senior_median: ", senior_median_age)

between = demographics[(demographics['Under 30'] == 0.0) & (demographics['Senior Citizen'] == 0.0) & demographics['Age'].notnull()]
between_median_age = between['Age'].median()
print("between_median: ", between_median_age)

above_30 = demographics[(demographics['Under 30'] == 0.0) & demographics['Age'].notnull()]
above_30_median_age = above_30['Age'].median()
print("above_30_median: ", above_30_median_age)

under_65 = demographics[(demographics['Senior Citizen'] == 0.0) & demographics['Age'].notnull()]
under_65_median_age = under_65['Age'].median()
print("under_65_median: ", under_65_median_age)

under_30_median:  24.0
senior_median:  73.0
between_median:  47.0
above_30_median:  51.0
under_65_median:  42.0

# fill in nan by median

In [ ]:
# demographics.loc[demographics['Age'].isna() & (demographics['Under 30'] == 1.0), 'Age'] = under_30_median_age
# demographics.loc[demographics['Age'].isna() & (demographics['Senior Citizen'] == 1.0), 'Age'] = senior_median_age
# demographics.loc[demographics['Age'].isna() & (demographics['Under 30'] == 0.0) & (demographics['Senior Citizen'] == 0.0), 'Age'] = between_median_age
# demographics.loc[demographics['Age'].isna() & (demographics['Under 30'] == 0.0), 'Age'] = above_30_median_age
# demographics.loc[demographics['Age'].isna() & (demographics['Senior Citizen'] == 0.0), 'Age'] = under_65_median_age
# print(demographics.isna().sum())

Customer ID               0
Count                   770
Gender                  770
Age                       8
Under 30                 87
Senior Citizen           77
Married                 770
Dependents              770
Number of Dependents    770
dtype: int64

In [ ]:
demographics[demographics['Age'].isna()]

     Customer ID  Count  Gender  ...  Married  Dependents  Number of Dependents
48    8800-JOOCF    1.0     0.0  ...      0.0         0.0                   0.0
451   9305-CDSKC    1.0     NaN  ...      1.0         1.0                   NaN
702   8225-BTJAU    1.0     1.0  ...      1.0         0.0                   0.0
2615  6689-KXGBO    1.0     NaN  ...      1.0         0.0                   0.0
2687  2748-MYRVK    1.0     NaN  ...      0.0         0.0                   0.0
3308  0897-FEGMU    1.0     1.0  ...      1.0         NaN                   0.0
5181  0725-CXOTM    1.0     0.0  ...      0.0         0.0                   0.0
6048  5313-FPXWG    1.0     1.0  ...      0.0         0.0                   0.0

[8 rows x 9 columns]

In [ ]:
demographics.loc[demographics['Number of Dependents'] > 0, ['Dependents']] = 1
demographics.loc[demographics['Number of Dependents'] == 0, ['Dependents']] = 0
demographics.loc[demographics['Dependents'] == 0, ['Number of Dependents']] = 0
demographics[(demographics['Dependents'] == 1) & (demographics['Number of Dependents'].isnull())]

     Customer ID  Count  Gender  ...  Married  Dependents  Number of Dependents
5     7284-BUYEC    1.0     0.0  ...      NaN         1.0                   NaN
451   9305-CDSKC    1.0     NaN  ...      1.0         1.0                   NaN
660   0524-IAVZO    1.0     0.0  ...      1.0         1.0                   NaN
679   5944-UGLLK    1.0     0.0  ...      1.0         1.0                   NaN
749   2097-YVPKN    1.0     1.0  ...      1.0         1.0                   NaN
...          ...    ...     ...  ...      ...         ...                   ...
6051  1293-HHSHJ    1.0     1.0  ...      1.0         1.0                   NaN
6063  6777-TGHTM    1.0     NaN  ...      1.0         1.0                   NaN
6064  5696-EXCYS    1.0     NaN  ...      1.0         1.0                   NaN
6087  0603-OLQDC    1.0     0.0  ...      1.0         1.0                   NaN
6114  1492-KGETH    NaN     1.0  ...      1.0         1.0                   NaN

[152 rows x 9 columns]

In [ ]:
num_dependents_median = demographics[(demographics['Dependents'] == 1) & demographics['Number of Dependents'].notnull()]['Number of Dependents'].median()
demographics.loc[demographics['Number of Dependents'].isna() & (demographics['Dependents'] == 1), 'Number of Dependents'] = num_dependents_median
demographics.isna().sum()

Customer ID               0
Count                   770
Gender                  770
Age                       8
Under 30                 87
Senior Citizen           77
Married                 770
Dependents               93
Number of Dependents     93
dtype: int64

In [ ]:
demographics[demographics['Dependents'].isna()]

     Customer ID  Count  Gender  ...  Married  Dependents  Number of Dependents
6     3458-IDMFK    1.0     0.0  ...      1.0         NaN                   NaN
39    2424-WVHPL    1.0     1.0  ...      0.0         NaN                   NaN
53    3115-CZMZD    1.0     1.0  ...      NaN         NaN                   NaN
175   1501-SGHBW    1.0     1.0  ...      0.0         NaN                   NaN
179   9101-BWFSS    1.0     0.0  ...      0.0         NaN                   NaN
...          ...    ...     ...  ...      ...         ...                   ...
5839  6250-CGGUN    1.0     1.0  ...      0.0         NaN                   NaN
5852  4510-HIMLV    1.0     0.0  ...      0.0         NaN                   NaN
5975  9360-AHGNL    1.0     1.0  ...      0.0         NaN                   NaN
6044  7503-MIOGA    1.0     NaN  ...      0.0         NaN                   NaN
6125  1816-FLZDK    NaN     NaN  ...      0.0         NaN                   NaN

[93 rows x 9 columns]

In [ ]:
demographics.to_csv('/content/drive/MyDrive/HTML final project/new_demographics.csv', index=False)